image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview

tasks:
  - name: Start Desktop
    command: |
      vncserver -kill :1 || true
      rm -rf /tmp/.X1-lock /tmp/.X11-unix/X1 || true
      vncserver :1 -geometry 1920x1080 -SecurityTypes None
      websockify --web=/usr/share/novnc/ --wrap-mode=ignore 6080 localhost:5901
